# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Alert:
  fields:
    default: email, address, last_sent, lat, lng, confirm_id, confirmed, radius_meters, lga_name
    list: email, address, last_sent, confirmed, radius_meters
    form: email, address, last_sent, lat, lng, confirm_id, confirmed, radius_meters, lga_name
  order_by: 
  relationships: 
  filters: 
  search: email, address
  application: PlanningAlerts

Authority:
  fields:
    default: full_name, short_name, feed_url, disabled, state, email
    list: full_name, disabled, state, email
    form: full_name, short_name, state, feed_url, email, disabled
    options:
      read_only: full_name, short_name, feed_url, state
  order_by: 
  relationships: applications
  filters: 
  search: full_name
  application: PlanningAlerts

Comment:
  fields:
    default: email, name, confirm_id, confirmed
    list: email, name, confirmed, text
    form: text, email, name, confirm_id, confirmed
    options:
      read_only: text, email, name, application, confirm_id, confirmed
  order_by:
  relationships:
  filters: 
  search: text, email
  application: PlanningAlerts
